; PlatformIO Project Configuration File

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

[env:car]
extends = env
build_src_filter =
    +<main.cpp>
    -<hand.cpp>

[env:hand]
extends = env
build_src_filter =
    +<hand.cpp>
    -<main.cpp>
